export let TOGGLE_LOGIN = 'TOGGLE_LOGIN'
export let USERNAME_BLUR = 'USERNAME_BLUR'
export let PASSWORD_BLUR = 'PASSWORD_BLUR'
export let CREATE_USER = 'CREATE_USER'
export let COOKIE = 'COOKIE'
export let LOGOUT = 'LOGOUT'
export let LOGIN = 'LOGIN'
export let INVALID_LOGIN = 'INVALID_LOGIN'
export let DISMISS_LOGIN_ALERT = 'DISMISS_LOGIN_ALERT'
export let CREATE_USER_ALERT = 'CREATE_USER_ALERT'
export let DEFAULT = 'DEFAULT'
export let SET_PAGE = 'SET_PAGE'
export let GET_ASSOCIATIONS = 'GET_ASSOCIATIONS'
export let AUTH='AUTH'
export let DISMISS_AUTH_ALERT='DISMISS_AUTH_ALERT'
export let AUTH_SUCCESS = 'AUTH_SUCCESS'
export let AUTH_FAIL = 'AUTH_FAIL'
export let REVOKE_AUTH = 'REVOKE_AUTH'

export let CHECK_CROWDDIT_AUTH_STATUS = 'CHECK_CROWDDIT_AUTH_STATUS'

export let HEROKU_BACKEND = 'https://crowddit-backend.herokuapp.com'
export let GH_PAGES = "https://indivism.github.io/crowddit"